# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('branch', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary'), ('?', 'Unknown')], default='?', max_length=1)),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('RACE', models.CharField(choices=[('A', 'Asian'), ('B', 'Black'), ('L', 'Latino'), ('W', 'White'), ('O', 'Other'), ('?', 'Unknown')], default='?', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
